/* ==========================================================================
   أونلاين كشك - Super Admin Panel Logic & Real-Time Analytics Integration Engine
   ========================================================================== */

let activeAddImages = [];
let activeEditImages = [];
let trafficChartInstance = null;
let locationChartInstance = null;
let selectedIframeElement = null;

document.addEventListener('DOMContentLoaded', async function () {
    
    // 1. تفعيل أزرار فتح السايدبار للموبايل
    initSidebarMobileToggle();

    // 2. مراقبة رفع الصور لإظهار الكروت المصغرة والتحكم بالصورة الرئيسية
    initImageFileInputListeners();

    // 3. تفعيل تفاعلية كروت الإحصائيات
    initStatCardsClickEvents();

    // 4. تفعيل النماذج المتقدمة (الرفض، العمولة، الأرصدة)
    initRejectPayoutFormListener();
    initAddCommissionFormListener();
    initManageUserBalanceFormListener();

    // 5. تفعيل نموذج إضافة القسم ومتجر جديد بـ Supabase بدون Reload
    initAddCategoryAndStoreForms();

    // 6. تفعيل الفلاتر والمزامنة الحية المباشرة (Live Preview Engine)
    initProductFilters();
    initLivePreviewSync();

    // 7. تهيئة تفاعلية الـ iFrame ومحرر الموقع الحي (Live View Mode)
    initLiveSiteIframeInteraction();

    // 8. تفعيل زر حفظ محرر الموقع الحي في Supabase
    initSiteContentCMSsaver();

    // 9. تحميل المتاجر والأقسام ديناميكياً
    await loadCategoriesAndStoresDropdowns();

    // 10. نموذج إضافة منتج جديد بمستوى Shopify احترافي لـ Supabase
    const addProductForm = document.getElementById('addProductForm');
    if (addProductForm) {
        addProductForm.addEventListener('submit', async function (e) {
            e.preventDefault();
            
            let client = window.supabaseClient;
            if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') {
                client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
            }

            if (!client) {
                showAdminToast('خطأ: لم يتم الاتصال بقاعدة البيانات.', 'error');
                return;
            }

            // رابط الأفيليت هو الحقل الإجباري الوحيد
            const affiliateUrlInput = document.getElementById('prodAffiliateUrl');
            const affiliateUrl = affiliateUrlInput ? affiliateUrlInput.value.trim() : '';
            if (!affiliateUrl) {
                showAdminToast('رابط الأفلييت إجباري لإضافة المنتج!', 'error');
                return;
            }

            const title = (document.getElementById('prodTitle')?.value.trim()) || 'عرض حصري جديد';
            const store = document.getElementById('prodStore')?.value || 'أمازون';
            const category = (document.getElementById('prodCategory')?.value.trim()) || 'عروض عامة';
            const brand = document.getElementById('prodBrand')?.value.trim() || '';
            const origPrice = parseFloat(document.getElementById('prodOriginalPrice')?.value || '0') || 0;
            const discPrice = parseFloat(document.getElementById('prodDiscountPrice')?.value || '0') || 0;
            const cashbackAmount = parseFloat(document.getElementById('prodCashbackAmount')?.value || '0') || 0;
            const couponCode = document.getElementById('prodCouponCode')?.value.trim().toUpperCase() || '';
            const stockStatus = document.getElementById('prodStockStatus')?.value || 'in_stock';
            const warranty = document.getElementById('prodWarranty')?.value.trim() || '';
            const showHome = document.getElementById('prodShowHome') ? (document.getElementById('prodShowHome').value === 'true') : true;
            const imageUrlInput = document.getElementById('prodImageUrl')?.value.trim() || '';
            const specs = document.getElementById('prodSpecs')?.value.trim() || '';
            const description = document.getElementById('prodDescription')?.value.trim() || '';

            // توليد الكلمات المفتاحية تلقائياً من الاسم والوصف فقط وتخزينها في قاعدة البيانات
            const autoGeneratedKeywords = generateAutoKeywords(title, description);

            let finalImages = [...activeAddImages];
            if (imageUrlInput && !finalImages.includes(imageUrlInput)) {
                finalImages.unshift(imageUrlInput);
            }

            const discountPercent = (origPrice > 0 && discPrice > 0 && origPrice > discPrice) ? Math.round(((origPrice - discPrice) / origPrice) * 100) : 0;
            const finalMainImage = finalImages.length > 0 ? finalImages[0] : (imageUrlInput || 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400');

            const submitBtn = addProductForm.querySelector('button[type="submit"]');
            if (submitBtn) {
                submitBtn.disabled = true;
                submitBtn.innerHTML = 'جاري الحفظ بالداتا بيز... <span class="spinner-border spinner-border-sm me-1"></span>';
            }

            const payload = {
                title: title,
                store_name: store,
                category: category,
                brand: brand,
                original_price: origPrice,
                discount_price: discPrice,
                discount_percentage: discountPercent,
                commission_amount: cashbackAmount,
                coupon_code: couponCode,
                stock_status: stockStatus,
                warranty: warranty,
                show_in_home: showHome,
                image_url: finalMainImage,
                affiliate_url: affiliateUrl,
                specs: specs,
                description: description,
                keywords: autoGeneratedKeywords,
                images: finalImages
            };

            try {
                let { data, error } = await client.from('products').insert([payload]).select();

                if (error) {
                    delete payload.specs;
                    delete payload.brand;
                    delete payload.warranty;
                    delete payload.stock_status;
                    
                    let retry = await client.from('products').insert([payload]).select();
                    if (retry.error) {
                        delete payload.images;
                        delete payload.description;
                        delete payload.keywords;
                        delete payload.coupon_code;
                        retry = await client.from('products').insert([payload]).select();
                    }
                    data = retry.data;
                    error = retry.error;
                }

                if (error) throw error;

                showAdminToast('🎉 تمت إضافة المنتج بنجاح وتوليد الكلمات المفتاحية وتأكيد البيانات!', 'success');
                
                const modalEl = document.getElementById('addProductModal');
                if (modalEl && typeof bootstrap !== 'undefined') {
                    const modal = bootstrap.Modal.getInstance(modalEl);
                    if (modal) modal.hide();
                }

                if (data && data.length > 0) {
                    openProductPreview(data[0]);
                }

                addProductForm.reset();
                activeAddImages = [];
                renderImageThumbnails('addImagesPreviewContainer', activeAddImages, 'add');

                loadProductsList();
                loadAdminStats();
                loadCategoriesAndStoresDropdowns();

            } catch (err) {
                console.error('Database Error:', err);
                showAdminToast('❌ خطأ في الإضافة: ' + err.message, 'error');
            } finally {
                if (submitBtn) {
                    submitBtn.disabled = false;
                    submitBtn.innerHTML = 'حفظ ونشر المنتج <i class="bi bi-check-lg ms-1"></i>';
                }
            }
        });
    }

    // 11. نموذج حفظ التعديلات على المنتج
    const editProductForm = document.getElementById('editProductForm');
    if (editProductForm) {
        editProductForm.addEventListener('submit', async function (e) {
            e.preventDefault();

            let client = window.supabaseClient;
            if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

            const prodId = document.getElementById('editProdId')?.value;
            if (!prodId) {
                showAdminToast('خطأ: معرّف المنتج غير متاح للتعديل', 'error');
                return;
            }

            const title = document.getElementById('editProdTitle')?.value.trim() || 'عرض أونلاين كشك';
            const store = document.getElementById('editProdStore')?.value || 'أمازون';
            const category = document.getElementById('editProdCategory')?.value.trim() || 'عروض';
            const brand = document.getElementById('editProdBrand')?.value.trim() || '';
            const origPrice = parseFloat(document.getElementById('editProdOriginalPrice')?.value || '0');
            const discPrice = parseFloat(document.getElementById('editProdDiscountPrice')?.value || '0');
            const cashbackAmount = parseFloat(document.getElementById('editProdCashbackAmount')?.value || '0');
            const couponCode = document.getElementById('editProdCouponCode')?.value.trim().toUpperCase() || '';
            const stockStatus = document.getElementById('editProdStockStatus')?.value || 'in_stock';
            const warranty = document.getElementById('editProdWarranty')?.value.trim() || '';
            const showHome = document.getElementById('editProdShowHome')?.value === 'true';
            const imageUrl = document.getElementById('editProdImageUrl')?.value.trim() || '';
            const affiliateUrl = document.getElementById('editProdAffiliateUrl')?.value.trim() || '';
            const specs = document.getElementById('editProdSpecs')?.value.trim() || '';
            const description = document.getElementById('editProdDescription')?.value.trim() || '';

            const autoGeneratedKeywords = generateAutoKeywords(title, description);

            let finalImages = [...activeEditImages];
            if (imageUrl && !finalImages.includes(imageUrl)) {
                finalImages.unshift(imageUrl);
            }

            const discountPercent = (origPrice > 0 && discPrice > 0 && origPrice > discPrice) ? Math.round(((origPrice - discPrice) / origPrice) * 100) : 0;

            const payload = {
                title: title,
                store_name: store,
                category: category,
                brand: brand,
                original_price: origPrice,
                discount_price: discPrice,
                discount_percentage: discountPercent,
                commission_amount: cashbackAmount,
                coupon_code: couponCode,
                stock_status: stockStatus,
                warranty: warranty,
                show_in_home: showHome,
                image_url: imageUrl || (finalImages[0] || 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400'),
                images: finalImages,
                affiliate_url: affiliateUrl,
                specs: specs,
                description: description,
                keywords: autoGeneratedKeywords
            };

            try {
                let { error } = await client.from('products').update(payload).eq('id', prodId);

                if (error) {
                    delete payload.specs;
                    delete payload.brand;
                    delete payload.warranty;
                    delete payload.stock_status;

                    const retry = await client.from('products').update(payload).eq('id', prodId);
                    error = retry.error;
                }

                if (error) throw error;

                showAdminToast('✅ تم تعديل المنتج وحفظ كافة التحديثات بنجاح!', 'success');
                const modalEl = document.getElementById('editProductModal');
                if (modalEl && typeof bootstrap !== 'undefined') {
                    const modal = bootstrap.Modal.getInstance(modalEl);
                    if (modal) modal.hide();
                }

                loadProductsList();
                loadCategoriesAndStoresDropdowns();

            } catch (err) {
                showAdminToast('خطأ في التعديل: ' + err.message, 'error');
            }
        });
    }

    // 12. نموذج إضافة الكوبونات
    const addCouponForm = document.getElementById('addCouponForm');
    if (addCouponForm) {
        addCouponForm.addEventListener('submit', async function (e) {
            e.preventDefault();

            let client = window.supabaseClient;
            if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

            const code = document.getElementById('coupCode')?.value.trim().toUpperCase();
            const store = document.getElementById('coupStore')?.value.trim();
            const label = document.getElementById('coupLabel')?.value.trim();
            const minSpend = document.getElementById('coupMinSpend')?.value.trim();
            const showHome = document.getElementById('coupShowHome') ? (document.getElementById('coupShowHome').value === 'true') : true;

            try {
                const { error } = await client
                    .from('coupons')
                    .insert([
                        {
                            code: code,
                            store_name: store,
                            discount_label: label,
                            min_spend: minSpend || 'عرض خاص',
                            min_order_value: minSpend || 'عرض خاص',
                            show_in_home: showHome
                        }
                    ]);

                if (error) throw error;

                showAdminToast('🎉 تمت إضافة الكوبون بنجاح!', 'success');
                addCouponForm.reset();
                loadCouponsList();
                loadAdminStats();

            } catch (err) {
                showAdminToast('❌ خطأ في إضافة الكوبون: ' + err.message, 'error');
            }
        });
    }

    // 13. ربط التبويبات بالمحملات الديناميكية
    initTabButtons();

    // تسجيل الخروج
    const adminLogoutBtn = document.getElementById('adminLogoutBtn');
    if (adminLogoutBtn) {
        adminLogoutBtn.addEventListener('click', async function () {
            let client = window.supabaseClient;
            if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
            if (client) await client.auth.signOut();
            window.location.href = '../login.html';
        });
    }

    // التحميل الأولي
    loadAdminStats();
    loadProductsList();
    loadPayoutRequests();
    loadCategoriesList();
    loadStoresList();
    loadBannersList();
    loadUsersList();
    loadNewsletterSubscribers();
    loadContactMessages();
    loadAdminCommissionsList();
});

// 🌟 دالة توليد الكلمات المفتاحية أوتوماتيكياً (Auto Keywords Engine)
function generateAutoKeywords(title, description) {
    const combinedText = `${title || ''} ${description || ''}`;
    const cleanText = combinedText.replace(/[^\w\u0621-\u064A\s]/gi, ' ');
    const words = cleanText.split(/\s+/).filter(w => w.length > 2);
    const uniqueWords = [...new Set(words)];
    return uniqueWords.slice(0, 15).join(', ');
}

// 🌟 التنقل بين Tabs الإدخال بنمط Shopify Style
window.switchShopifyTab = function(type, sectionKey, btnEl) {
    const parentModal = btnEl.closest('.modal-body');
    if (!parentModal) return;

    const allTabs = parentModal.querySelectorAll('.shopify-tab-btn');
    allTabs.forEach(b => b.classList.remove('active'));
    btnEl.classList.add('active');

    const allSections = parentModal.querySelectorAll('.shopify-tab-content');
    allSections.forEach(s => s.classList.add('d-none'));

    const targetSection = parentModal.querySelector(`#${type}TabSection_${sectionKey}`);
    if (targetSection) {
        targetSection.classList.remove('d-none');
    }
};

// 🌟 إضافة الأقسام والمتاجر في Supabase بدون Reload
function initAddCategoryAndStoreForms() {
    const addCategoryForm = document.getElementById('addCategoryForm');
    if (addCategoryForm) {
        addCategoryForm.addEventListener('submit', async function(e) {
            e.preventDefault();
            const catName = document.getElementById('newCatName')?.value.trim();
            const showHome = document.getElementById('newCatShowHome')?.value === 'true';

            if (!catName) return;

            try {
                let client = window.supabaseClient;
                if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

                const { error } = await client.from('categories').insert([{ name: catName, show_in_home: showHome }]);
                if (error) throw error;

                showAdminToast('🎉 تمت إضافة القسم بنجاح وفحصه في قاعدة البيانات!', 'success');
                addCategoryForm.reset();
                loadCategoriesList();
                loadCategoriesAndStoresDropdowns();
            } catch (err) {
                showAdminToast('خطأ في إضافة القسم: ' + err.message, 'error');
            }
        });
    }

    const addStoreForm = document.getElementById('addStoreForm');
    if (addStoreForm) {
        addStoreForm.addEventListener('submit', async function(e) {
            e.preventDefault();
            const storeName = document.getElementById('newStoreName')?.value.trim();
            const logoUrl = document.getElementById('newStoreLogoUrl')?.value.trim();
            const storeUrl = document.getElementById('newStoreUrl')?.value.trim();
            const showNav = document.getElementById('newStoreShowInNavbar')?.value === 'true';
            const showStoresPage = document.getElementById('newStoreShowInStoresPage')?.value === 'true';

            if (!storeName) return;

            try {
                let client = window.supabaseClient;
                if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

                const { error } = await client.from('stores').insert([{
                    name: storeName,
                    logo_url: logoUrl || '',
                    store_url: storeUrl || '',
                    show_in_navbar: showNav,
                    show_in_stores_page: showStoresPage
                }]);
                if (error) throw error;

                showAdminToast('🎉 تمت إضافة المتجر بنجاح وحفظه في قاعدة البيانات!', 'success');
                addStoreForm.reset();
                loadStoresList();
                loadCategoriesAndStoresDropdowns();
            } catch (err) {
                showAdminToast('خطأ في إضافة المتجر: ' + err.message, 'error');
            }
        });
    }
}

// --------------------------------------------------------------------------
// 🌟 1. نظام رؤية حية للموقع المباشر (Live View Only - Clean Window)
// --------------------------------------------------------------------------

function initLiveSiteIframeInteraction() {
    const iframe = document.getElementById('liveSiteIframe');
    if (iframe) {
        iframe.addEventListener('load', function () {
            try {
                const iframeDoc = iframe.contentDocument || iframe.contentWindow.document;
                if (iframeDoc) {
                    // تحويل الإطار إلى رؤية حية نظيفة وتفاعلية مثل الموقع تماماً بدون فريم برتقالي
                    const style = iframeDoc.createElement('style');
                    style.innerHTML = `
                        /* رؤية حية ونظيفة للموقع للمعاينة فقط */
                        body { user-select: auto !important; }
                    `;
                    iframeDoc.head.appendChild(style);
                }
            } catch (err) {
                console.warn('تنبيه معاينة الـ iFrame:', err.message);
            }
        });
    }
}

function openLiveElementEditorModal(data, targetDOMElement = null) {
    // تم إلغاء المودال التلقائي للتحرير لجعل المعاينة نظيفة ورؤية حية واقعية 100%
}

function initSiteContentCMSsaver() {
    // نظام الحفظ بداخل المعاينة الحية
}

function closeLiveElementModal() {
    const modalEl = document.getElementById('liveSiteElementEditModal');
    if (modalEl && typeof bootstrap !== 'undefined') {
        const modal = bootstrap.Modal.getInstance(modalEl);
        if (modal) modal.hide();
    }
}

// --------------------------------------------------------------------------
// 🌟 2. تفعيل التحكم المباشر بالمعاينة والمزامنة الحية (Live Product Preview)
// --------------------------------------------------------------------------

window.toggleProductPreviewMode = function(mode) {
    const fullContainer = document.getElementById('previewFullPageContainer');
    const cardContainer = document.getElementById('previewCardContainer');
    const btnFull = document.getElementById('btnPreviewFullPage');
    const btnCard = document.getElementById('btnPreviewCard');

    if (mode === 'full') {
        if (fullContainer) fullContainer.classList.remove('d-none');
        if (cardContainer) cardContainer.classList.add('d-none');
        if (btnFull) btnFull.classList.add('active');
        if (btnCard) btnCard.classList.remove('active');
    } else {
        if (fullContainer) fullContainer.classList.add('d-none');
        if (cardContainer) cardContainer.classList.remove('d-none');
        if (btnCard) btnCard.classList.add('active');
        if (btnFull) btnFull.classList.remove('active');
    }
};

window.switchVirtualPage = function(pageUrl, btnEl) {
    const iframe = document.getElementById('liveSiteIframe');
    if (iframe) {
        iframe.src = pageUrl;
    }

    const allBtns = document.querySelectorAll('.page-switcher-btn');
    allBtns.forEach(b => b.classList.remove('active'));
    if (btnEl) btnEl.classList.add('active');

    showAdminToast('تم فتح المعاينة الحية للصفحة المختارة!', 'info');
};

function initLivePreviewSync() {
    const liveInputs = document.querySelectorAll('.live-input, .edit-live-input');
    liveInputs.forEach(input => {
        input.addEventListener('input', updateLiveVirtualPreview);
        input.addEventListener('change', updateLiveVirtualPreview);
    });
}

// 🌟 تحديث وإخفاء أي حقل فارغ من المعاينة الفيرشوال فوراً
function updateLiveVirtualPreview() {
    const title = document.getElementById('prodTitle')?.value.trim() || 'عنوان المنتج...';
    const store = document.getElementById('prodStore')?.value || 'المتجر';
    const category = document.getElementById('prodCategory')?.value || 'القسم';
    const brand = document.getElementById('prodBrand')?.value.trim() || '';
    const origPrice = parseFloat(document.getElementById('prodOriginalPrice')?.value || '0') || 0;
    const discPrice = parseFloat(document.getElementById('prodDiscountPrice')?.value || '0') || 0;
    const cashback = parseFloat(document.getElementById('prodCashbackAmount')?.value || '0') || 0;
    const couponCode = document.getElementById('prodCouponCode')?.value.trim().toUpperCase() || '';
    const stockStatus = document.getElementById('prodStockStatus')?.value || 'in_stock';
    const specsText = document.getElementById('prodSpecs')?.value.trim() || '';
    const descText = document.getElementById('prodDescription')?.value.trim() || '';
    const imageUrl = document.getElementById('prodImageUrl')?.value.trim() || (activeAddImages[0] || 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300');

    const discountPercent = (origPrice > 0 && discPrice > 0 && origPrice > discPrice) ? Math.round(((origPrice - discPrice) / origPrice) * 100) : 0;

    // 1. تحديث كارت المعاينة المصغر
    if (document.getElementById('liveCardTitle')) document.getElementById('liveCardTitle').innerText = title;
    if (document.getElementById('liveCardStore')) document.getElementById('liveCardStore').innerText = store;
    if (document.getElementById('liveCardCategory')) document.getElementById('liveCardCategory').innerText = category;
    if (document.getElementById('liveCardDiscPrice')) document.getElementById('liveCardDiscPrice').innerText = `${discPrice} ج.م`;
    if (document.getElementById('liveCardOrigPrice')) document.getElementById('liveCardOrigPrice').innerText = `${origPrice} ج.م`;
    if (document.getElementById('liveBadgeDisc')) document.getElementById('liveBadgeDisc').innerText = `-${discountPercent}%`;
    if (document.getElementById('liveCardCashback')) document.getElementById('liveCardCashback').innerText = `كاش باك ${cashback} ج.م`;
    if (document.getElementById('liveCardImg')) document.getElementById('liveCardImg').src = imageUrl;

    const cardOutOfStockBadge = document.getElementById('liveOutOfStockBadgeCard');
    if (cardOutOfStockBadge) {
        if (stockStatus === 'out_of_stock') {
            cardOutOfStockBadge.classList.remove('d-none');
        } else {
            cardOutOfStockBadge.classList.add('d-none');
        }
    }

    // 2. تحديث معاينة صفحة تفاصيل المنتج الكاملة وإخفاء الحقول الفارغة
    if (document.getElementById('livePageTitle')) document.getElementById('livePageTitle').innerText = title;
    if (document.getElementById('livePageStore')) document.getElementById('livePageStore').innerText = store;
    
    // الماركة (إخفاء إن كانت فارغة)
    const brandBadge = document.getElementById('livePageBrand');
    if (brandBadge) {
        if (brand) {
            brandBadge.innerText = brand;
            brandBadge.classList.remove('d-none');
        } else {
            brandBadge.classList.add('d-none');
        }
    }

    if (document.getElementById('livePageMainImg')) document.getElementById('livePageMainImg').src = imageUrl;

    const pageOutOfStockBadge = document.getElementById('liveOutOfStockBadgePage');
    if (pageOutOfStockBadge) {
        if (stockStatus === 'out_of_stock') {
            pageOutOfStockBadge.classList.remove('d-none');
        } else {
            pageOutOfStockBadge.classList.add('d-none');
        }
    }

    if (document.getElementById('livePagePrice')) document.getElementById('livePagePrice').innerText = `${discPrice} ج.م`;
    if (document.getElementById('livePageOrigPrice')) document.getElementById('livePageOrigPrice').innerText = `${origPrice} ج.م`;
    if (document.getElementById('livePageCashback')) document.getElementById('livePageCashback').innerText = `كاش باك ${cashback} ج.م`;

    // الكوبون
    const couponBox = document.getElementById('livePageCouponBox');
    if (couponBox) {
        if (couponCode) {
            if (document.getElementById('livePageCoupon')) document.getElementById('livePageCoupon').innerText = couponCode;
            couponBox.classList.remove('d-none');
        } else {
            couponBox.classList.add('d-none');
        }
    }

    // المواصفات الفنية
    const specsBox = document.getElementById('livePageSpecsBox');
    if (specsBox) {
        if (specsText) {
            if (document.getElementById('livePageSpecs')) document.getElementById('livePageSpecs').innerText = specsText;
            specsBox.classList.remove('d-none');
        } else {
            specsBox.classList.add('d-none');
        }
    }

    // الوصف
    const descBox = document.getElementById('livePageDescBox');
    if (descBox) {
        if (descText) {
            if (document.getElementById('livePageDesc')) document.getElementById('livePageDesc').innerText = descText;
            descBox.classList.remove('d-none');
        } else {
            descBox.classList.add('d-none');
        }
    }
}

// --------------------------------------------------------------------------
// 🌟 إدارة رفع وتصغير الصور وتعيين الرئيسية
// --------------------------------------------------------------------------

function renderImageThumbnails(containerId, imagesArr, type) {
    const container = document.getElementById(containerId);
    if (!container) return;

    if (!imagesArr || imagesArr.length === 0) {
        container.innerHTML = `<span class="text-muted fs-8">لا توجد صور مضافة للمعاينة...</span>`;
        return;
    }

    container.innerHTML = imagesArr.map((imgSrc, index) => `
        <div class="position-relative d-inline-block border ${index === 0 ? 'border-primary border-2' : ''} rounded-3 p-1 bg-white shadow-sm" style="width: 80px; height: 80px;">
            <img src="${imgSrc}" class="w-100 h-100 object-fit-cover rounded-2">
            ${index === 0 ? '<span class="badge bg-primary position-absolute bottom-0 start-50 translate-middle-x fs-9" style="font-size:0.6rem;">رئيسية</span>' : ''}
            <div class="position-absolute top-0 start-0 translate-middle d-flex gap-1" style="z-index: 10;">
                <button type="button" onclick="setAsMainImage('${type}', ${index})" class="btn btn-warning btn-sm rounded-circle p-0 d-flex align-items-center justify-content-center" style="width: 20px; height: 20px;" title="تعيين كصورة رئيسية ⭐">
                    <i class="bi bi-star-fill text-dark fs-9"></i>
                </button>
                <button type="button" onclick="removeSingleImage('${type}', ${index})" class="btn btn-danger btn-sm rounded-circle p-0 d-flex align-items-center justify-content-center" style="width: 20px; height: 20px;" title="حذف">
                    <i class="bi bi-x-lg text-white fs-9"></i>
                </button>
            </div>
        </div>
    `).join('');

    const mainImgInput = document.getElementById('prodImageUrl');
    if (mainImgInput && imagesArr.length > 0) {
        mainImgInput.value = imagesArr[0];
    }

    updateLiveVirtualPreview();
}

function setAsMainImage(type, index) {
    if (type === 'add') {
        const selected = activeAddImages.splice(index, 1)[0];
        activeAddImages.unshift(selected);
        renderImageThumbnails('addImagesPreviewContainer', activeAddImages, 'add');
    } else {
        const selected = activeEditImages.splice(index, 1)[0];
        activeEditImages.unshift(selected);
        renderImageThumbnails('editImagesPreviewContainer', activeEditImages, 'edit');
    }
    showAdminToast('تم تعيين هذه الصورة كصورة رئيسية للمنتج ⭐', 'info');
}

function removeSingleImage(type, index) {
    if (type === 'add') {
        activeAddImages.splice(index, 1);
        renderImageThumbnails('addImagesPreviewContainer', activeAddImages, 'add');
    } else {
        activeEditImages.splice(index, 1);
        renderImageThumbnails('editImagesPreviewContainer', activeEditImages, 'edit');
    }
}

function initSidebarMobileToggle() {
    const toggleBtn = document.getElementById('toggleSidebarBtn');
    const sidebar = document.getElementById('adminSidebar');
    if (toggleBtn && sidebar) {
        toggleBtn.addEventListener('click', () => {
            sidebar.classList.toggle('show');
        });
    }
}

function initProductFilters() {
    const catFilter = document.getElementById('adminProductCategoryFilter');
    const storeFilter = document.getElementById('adminProductStoreFilter');

    if (catFilter) catFilter.addEventListener('change', loadProductsList);
    if (storeFilter) storeFilter.addEventListener('change', loadProductsList);
}

function initStatCardsClickEvents() {
    const cardUsers = document.getElementById('statCardUsers');
    const cardProducts = document.getElementById('statCardProducts');
    const cardCoupons = document.getElementById('statCardCoupons');
    const cardPayouts = document.getElementById('statCardPayouts');

    if (cardUsers) cardUsers.addEventListener('click', () => triggerTabClick('tab-users-btn'));
    if (cardProducts) cardProducts.addEventListener('click', () => triggerTabClick('tab-products-btn'));
    if (cardCoupons) cardCoupons.addEventListener('click', () => triggerTabClick('tab-coupons-btn'));
    if (cardPayouts) cardPayouts.addEventListener('click', () => triggerTabClick('tab-payouts-btn'));
}

function triggerTabClick(btnId) {
    const btn = document.getElementById(btnId);
    if (btn) btn.click();
}

function initImageFileInputListeners() {
    const addFileInput = document.getElementById('prodImageFiles');
    if (addFileInput) {
        addFileInput.addEventListener('change', function (e) {
            handleFilesToDataUrls(e.target.files, function (base64Array) {
                activeAddImages = [...activeAddImages, ...base64Array];
                renderImageThumbnails('addImagesPreviewContainer', activeAddImages, 'add');
            });
        });
    }

    const editFileInput = document.getElementById('editProdImageFiles');
    if (editFileInput) {
        editFileInput.addEventListener('change', function (e) {
            handleFilesToDataUrls(e.target.files, function (base64Array) {
                activeEditImages = [...activeEditImages, ...base64Array];
                renderImageThumbnails('editImagesPreviewContainer', activeEditImages, 'edit');
            });
        });
    }
}

function handleFilesToDataUrls(files, callback) {
    if (!files || files.length === 0) return;
    let loaded = [];
    let count = files.length;

    Array.from(files).forEach(file => {
        const reader = new FileReader();
        reader.onload = function (e) {
            loaded.push(e.target.result);
            if (loaded.length === count) {
                callback(loaded);
            }
        };
        reader.readAsDataURL(file);
    });
}

function initTabButtons() {
    const productsTabBtn = document.getElementById('tab-products-btn');
    if (productsTabBtn) productsTabBtn.addEventListener('click', loadProductsList);

    const analyticsTabBtn = document.getElementById('tab-analytics-btn');
    if (analyticsTabBtn) analyticsTabBtn.addEventListener('click', loadAnalyticsData);

    const commissionsTabBtn = document.getElementById('tab-commissions-btn');
    if (commissionsTabBtn) {
        commissionsTabBtn.addEventListener('click', () => {
            loadAdminCommissionsList();
            populateUsersDropdownForCommission();
        });
    }

    const couponsTabBtn = document.getElementById('tab-coupons-btn');
    if (couponsTabBtn) couponsTabBtn.addEventListener('click', loadCouponsList);

    const payoutsTabBtn = document.getElementById('tab-payouts-btn');
    if (payoutsTabBtn) payoutsTabBtn.addEventListener('click', loadPayoutRequests);

    const usersTabBtn = document.getElementById('tab-users-btn');
    if (usersTabBtn) usersTabBtn.addEventListener('click', loadUsersList);

    const categoriesTabBtn = document.getElementById('tab-categories-btn');
    if (categoriesTabBtn) categoriesTabBtn.addEventListener('click', () => {
        loadCategoriesList();
        loadStoresList();
    });

    const bannersTabBtn = document.getElementById('tab-banners-btn');
    if (bannersTabBtn) bannersTabBtn.addEventListener('click', loadBannersList);

    const newsletterTabBtn = document.getElementById('tab-newsletter-btn');
    if (newsletterTabBtn) newsletterTabBtn.addEventListener('click', () => {
        loadNewsletterSubscribers();
        loadContactMessages();
    });
}

async function loadCategoriesAndStoresDropdowns() {
    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
        if (!client) return;

        const { data: cats } = await client.from('categories').select('name').order('name');
        const catFilter = document.getElementById('adminProductCategoryFilter');
        const prodCatSelect = document.getElementById('prodCategory');
        const editCatSelect = document.getElementById('editProdCategory');

        const defaultCategories = ['إلكترونيات', 'موضة وأزياء', 'أدوات منزلية', 'عطور وتجميل', 'ألعاب أطفال'];
        const dbCatNames = (cats || []).map(c => c.name);
        const allCategories = [...new Set([...defaultCategories, ...dbCatNames].filter(Boolean))];

        const catOptions = allCategories.map(c => `<option value="${c}">${c}</option>`).join('');
        if (catFilter) catFilter.innerHTML = `<option value="ALL">جميع الأقسام</option>` + catOptions;
        if (prodCatSelect) prodCatSelect.innerHTML = `<option value="">اختر القسم...</option>` + catOptions;
        if (editCatSelect) editCatSelect.innerHTML = `<option value="">اختر القسم...</option>` + catOptions;

        const { data: storesDB } = await client.from('stores').select('name').order('name');
        const { data: prods } = await client.from('products').select('store_name');
        
        const dbStoreNames = (storesDB || []).map(s => s.name);
        const prodStoreNames = (prods || []).map(p => p.store_name);
        
        const defaultStores = ['أمازون', 'نون', 'جوميا', 'علي إكسبريس', 'كارفور', 'سبينيس', 'بي تك'];
        const allStores = [...new Set([...defaultStores, ...dbStoreNames, ...prodStoreNames].filter(Boolean))];

        const storeFilter = document.getElementById('adminProductStoreFilter');
        const prodStoreSelect = document.getElementById('prodStore');
        const editStoreSelect = document.getElementById('editProdStore');
        const coupStoreSelect = document.getElementById('coupStore');

        const storeOptions = allStores.map(s => `<option value="${s}">${s}</option>`).join('');
        if (storeFilter) storeFilter.innerHTML = `<option value="ALL">جميع المتاجر</option>` + storeOptions;
        if (prodStoreSelect) prodStoreSelect.innerHTML = storeOptions;
        if (editStoreSelect) editStoreSelect.innerHTML = storeOptions;
        if (coupStoreSelect) coupStoreSelect.innerHTML = storeOptions;

    } catch (err) {
        console.warn('تنبيه جلب المتاجر والأقسام:', err.message);
    }
}

async function loadAdminStats() {
    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
        if (!client) return;

        const { count: usersCount } = await client.from('profiles').select('*', { count: 'exact', head: true });
        const { count: productsCount } = await client.from('products').select('*', { count: 'exact', head: true });
        const { count: couponsCount } = await client.from('coupons').select('*', { count: 'exact', head: true });
        const { count: payoutsCount } = await client.from('payout_requests').select('*', { count: 'exact', head: true }).eq('status', 'pending');

        if (document.getElementById('statUsersCount')) document.getElementById('statUsersCount').innerText = usersCount || 0;
        if (document.getElementById('statProductsCount')) document.getElementById('statProductsCount').innerText = productsCount || 0;
        if (document.getElementById('statCouponsCount')) document.getElementById('statCouponsCount').innerText = couponsCount || 0;
        if (document.getElementById('statPayoutsCount')) document.getElementById('statPayoutsCount').innerText = payoutsCount || 0;

    } catch (err) {
        console.warn('الإحصائيات:', err.message);
    }
}

async function loadProductsList() {
    const tableBody = document.getElementById('adminProductsTable');
    if (!tableBody) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        let query = client.from('products').select('*').order('created_at', { ascending: false });

        const catVal = document.getElementById('adminProductCategoryFilter')?.value;
        const storeVal = document.getElementById('adminProductStoreFilter')?.value;

        if (catVal && catVal !== 'ALL') {
            query = query.ilike('category', `%${catVal}%`);
        }
        if (storeVal && storeVal !== 'ALL') {
            query = query.eq('store_name', storeVal);
        }

        const { data: products, error } = await query;
        if (error) throw error;

        if (products && products.length > 0) {
            tableBody.innerHTML = products.map(p => `
                <tr>
                    <td class="text-start fw-bold">
                        <img src="${p.image_url || 'https://cdn-icons-png.flaticon.com/512/3514/3514491.png'}" width="36" height="36" class="rounded-2 me-2 object-fit-cover" onerror="this.src='https://cdn-icons-png.flaticon.com/512/3514/3514491.png'">
                        ${p.title}
                        ${p.coupon_code ? `<span class="badge bg-purple-soft text-purple border border-purple-subtle ms-1 fs-9"><i class="bi bi-ticket-perforated me-1"></i>${p.coupon_code}</span>` : ''}
                    </td>
                    <td>
                        <span class="badge bg-light text-dark border d-block mb-1">${p.store_name}</span>
                        <small class="text-muted fs-9">${p.category || 'عام'}</small>
                    </td>
                    <td><del class="text-muted">${p.original_price || 0}</del> / <strong class="text-purple">${p.discount_price || 0} ج.م</strong></td>
                    <td>
                        <span class="badge ${p.stock_status === 'out_of_stock' ? 'bg-danger' : (p.stock_status === 'limited' ? 'bg-warning text-dark' : 'bg-success')} rounded-pill px-2 py-1 fs-9">
                            ${p.stock_status === 'out_of_stock' ? 'نفدت الكمية' : (p.stock_status === 'limited' ? 'قطع قليلة' : 'متوفر')}
                        </span>
                    </td>
                    <td class="fw-bold text-success">${p.commission_amount || 0} ج.م</td>
                    <td>
                        <button onclick="editProduct('${p.id}')" class="btn btn-purple-soft btn-sm rounded-pill px-2 fs-9 me-1">تعديل <i class="bi bi-pencil"></i></button>
                        <button onclick="deleteProduct('${p.id}')" class="btn btn-outline-danger btn-sm rounded-pill px-2 fs-9">حذف <i class="bi bi-trash"></i></button>
                    </td>
                </tr>
            `).join('');
        } else {
            tableBody.innerHTML = `<tr><td colspan="6" class="text-muted py-3">لا توجد منتجات مضافة مطابقة للفلترة حالياً</td></tr>`;
        }
    } catch (err) {
        tableBody.innerHTML = `<tr><td colspan="6" class="text-muted py-3">لا توجد منتجات مضافة حالياً</td></tr>`;
    }
}

// 🌟 جلب التحليلات الحقيقية الفعلية من قاعدة البيانات Supabase (analytics_events)
async function loadAnalyticsData() {
    if (typeof ApexCharts === 'undefined') return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') {
            client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
        }

        if (!client) return;

        // جلب الأحداث المسجلة في جدول التحليلات
        const { data: analyticsEvents, error } = await client
            .from('analytics_events')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) throw error;

        // 1. تجميع بيانات حركة الزيارات والضغطات اليومية
        const dailyViewsMap = {};
        const dailyClicksMap = {};
        const deviceMap = { 'Desktop': 0, 'Mobile': 0 };

        (analyticsEvents || []).forEach(evt => {
            const dateKey = new Date(evt.created_at).toLocaleDateString('ar-EG', { month: 'short', day: 'numeric' });
            
            if (evt.event_type === 'click') {
                dailyClicksMap[dateKey] = (dailyClicksMap[dateKey] || 0) + 1;
            } else {
                dailyViewsMap[dateKey] = (dailyViewsMap[dateKey] || 0) + 1;
            }

            if (evt.device_type === 'Mobile') {
                deviceMap['Mobile']++;
            } else {
                deviceMap['Desktop']++;
            }
        });

        const categories = Object.keys(dailyViewsMap).length > 0 ? Object.keys(dailyViewsMap).reverse() : ['اليوم'];
        const viewsData = categories.map(k => dailyViewsMap[k] || 0);
        const clicksData = categories.map(k => dailyClicksMap[k] || 0);

        // 2. رسم المخطط البياني للحركة اليومية (Traffic Area Chart)
        const trafficEl = document.getElementById('trafficChart');
        if (trafficEl) {
            trafficEl.innerHTML = '';
            const trafficOptions = {
                chart: { type: 'area', height: 300, toolbar: { show: false } },
                colors: ['#9333ea', '#10b981'],
                series: [
                    { name: 'زيارات الصفحات الفردية', data: viewsData.length > 0 ? viewsData : [1] },
                    { name: 'نقرات زر الشراء والكاش باك', data: clicksData.length > 0 ? clicksData : [0] }
                ],
                xaxis: { categories: categories },
                stroke: { curve: 'smooth', width: 2 },
                fill: { type: 'gradient', gradient: { shadeIntensity: 1, opacityFrom: 0.4, opacityTo: 0.05 } }
            };
            trafficChartInstance = new ApexCharts(trafficEl, trafficOptions);
            trafficChartInstance.render();
        }

        // 3. رسم المخطط البياني لتوزيع أجهزة الزوار (Devices Donut Chart)
        const locationEl = document.getElementById('locationChart');
        if (locationEl) {
            locationEl.innerHTML = '';
            const totalDesktop = deviceMap['Desktop'] || 1;
            const totalMobile = deviceMap['Mobile'] || 0;

            const locationOptions = {
                chart: { type: 'donut', height: 300 },
                colors: ['#9333ea', '#3b82f6'],
                series: [totalDesktop, totalMobile],
                labels: ['أجهزة الكمبيوتر (Desktop)', 'الهواتف الذكية (Mobile)']
            };
            locationChartInstance = new ApexCharts(locationEl, locationOptions);
            locationChartInstance.render();
        }

        // 4. تعبئة جدول أكثر المنتجات والصفحات زيارة
        const topTable = document.getElementById('analyticsTopPagesTable');
        if (topTable) {
            const pageStatsMap = {};
            (analyticsEvents || []).forEach(evt => {
                const path = evt.page_path || '/';
                if (!pageStatsMap[path]) {
                    pageStatsMap[path] = { views: 0, clicks: 0 };
                }
                if (evt.event_type === 'click') {
                    pageStatsMap[path].clicks++;
                } else {
                    pageStatsMap[path].views++;
                }
            });

            const sortedPages = Object.keys(pageStatsMap);
            if (sortedPages.length > 0) {
                topTable.innerHTML = sortedPages.map(page => {
                    const stats = pageStatsMap[page];
                    const conversionRate = stats.views > 0 ? Math.round((stats.clicks / stats.views) * 100) : 0;
                    return `
                        <tr>
                            <td class="fw-bold text-start text-purple">${page}</td>
                            <td class="fw-bold">${stats.views} زيارة</td>
                            <td class="text-success fw-bold">${stats.clicks} نقرة</td>
                            <td><span class="badge bg-purple-soft text-purple fs-9">${conversionRate}% تحويل</span></td>
                        </tr>
                    `;
                }).join('');
            } else {
                topTable.innerHTML = `<tr><td colspan="4" class="text-muted py-3">جاري تجميع أحداث الزيارات والنقرات المباشرة...</td></tr>`;
            }
        }

    } catch (err) {
        console.warn('تنبيه جلب التحليلات الحقيقية:', err.message);
    }
}

async function editProduct(id) {
    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: p, error } = await client.from('products').select('*').eq('id', id).single();
        if (error || !p) throw new Error('تعذر جلب بيانات المنتج');

        const setVal = (elementId, value) => {
            const el = document.getElementById(elementId);
            if (el) el.value = value !== null && value !== undefined ? value : '';
        };

        setVal('editProdId', p.id);
        setVal('editProdTitle', p.title);
        setVal('editProdStore', p.store_name || 'أمازون');
        setVal('editProdCategory', p.category);
        setVal('editProdBrand', p.brand || '');
        setVal('editProdOriginalPrice', p.original_price);
        setVal('editProdDiscountPrice', p.discount_price);
        setVal('editProdCashbackAmount', p.commission_amount || '0');
        setVal('editProdCouponCode', p.coupon_code || '');
        setVal('editProdStockStatus', p.stock_status || 'in_stock');
        setVal('editProdShowHome', p.show_in_home ? 'true' : 'false');
        setVal('editProdWarranty', p.warranty || '');
        setVal('editProdImageUrl', p.image_url);
        setVal('editProdAffiliateUrl', p.affiliate_url);
        setVal('editProdSpecs', p.specs || '');
        setVal('editProdDescription', p.description);

        activeEditImages = (p.images && p.images.length > 0) ? p.images : (p.image_url ? [p.image_url] : []);
        renderImageThumbnails('editImagesPreviewContainer', activeEditImages, 'edit');

        const modalEl = document.getElementById('editProductModal');
        if (modalEl && typeof bootstrap !== 'undefined') {
            const modal = new bootstrap.Modal(modalEl);
            modal.show();
        }

    } catch (err) {
        showAdminToast('خطأ: ' + err.message, 'error');
    }
}

function openProductPreview(p) {
    if (!p) return;
    document.getElementById('previewModalImg').src = p.image_url || 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400';
    document.getElementById('previewModalStore').innerText = p.store_name || 'أمازون';
    document.getElementById('previewModalTitle').innerText = p.title || 'منتج كشك';
    document.getElementById('previewModalDiscPrice').innerText = `${p.discount_price || 0} ج.م`;
    document.getElementById('previewModalOrigPrice').innerText = `${p.original_price || 0} ج.م`;
    document.getElementById('previewModalDesc').innerText = p.description || 'لا يوجد وصف مضاف لهذا المنتج.';
    document.getElementById('previewModalLink').href = p.affiliate_url || '#';

    const modal = new bootstrap.Modal(document.getElementById('productPreviewModal'));
    modal.show();
}

async function deleteProduct(id) {
    const confirmed = await showAdminConfirm({
        title: 'حذف المنتج',
        message: 'هل أنت متأكد من حذف هذا المنتج نهائياً من قاعدة البيانات؟',
        confirmText: 'حذف الآن',
        type: 'danger'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
        const { error } = await client.from('products').delete().eq('id', id);
        if (error) throw error;
        showAdminToast('تم حذف المنتج بنجاح!', 'success');
        loadProductsList();
        loadAdminStats();
    } catch (err) {
        showAdminToast('خطأ أثناء الحذف: ' + err.message, 'error');
    }
}

async function loadCouponsList() {
    const tableBody = document.getElementById('adminCouponsTable');
    if (!tableBody) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: coupons, error } = await client.from('coupons').select('*').order('created_at', { ascending: false });
        if (error) throw error;

        if (coupons && coupons.length > 0) {
            tableBody.innerHTML = coupons.map(c => `
                <tr>
                    <td class="fw-bold text-purple">${c.code}</td>
                    <td>${c.store_name}</td>
                    <td><span class="badge bg-purple-soft text-purple fs-9">${c.discount_label}</span></td>
                    <td>${c.show_in_home ? '✅ نعم' : '❌ لا'}</td>
                    <td>
                        <button onclick="deleteCoupon('${c.id}')" class="btn btn-outline-danger btn-sm rounded-pill px-2 fs-9">حذف <i class="bi bi-trash"></i></button>
                    </td>
                </tr>
            `).join('');
        } else {
            tableBody.innerHTML = `<tr><td colspan="5" class="text-muted py-3">لا توجد كوبونات مضافة حالياً</td></tr>`;
        }
    } catch (err) {
        tableBody.innerHTML = `<tr><td colspan="5" class="text-muted py-3">لا توجد كوبونات مضافة حالياً</td></tr>`;
    }
}

async function deleteCoupon(id) {
    const confirmed = await showAdminConfirm({
        title: 'حذف الكوبون',
        message: 'هل أنت متأكد من حذف هذا الكوبون نهائياً؟',
        confirmText: 'حذف الكوبون',
        type: 'danger'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
        const { error } = await client.from('coupons').delete().eq('id', id);
        if (error) throw error;
        showAdminToast('تم حذف الكوبون بنجاح!', 'success');
        loadCouponsList();
        loadAdminStats();
    } catch (err) {
        showAdminToast('خطأ في الحذف: ' + err.message, 'error');
    }
}

async function loadPayoutRequests() {
    const tableBody = document.getElementById('adminPayoutsTable');
    if (!tableBody) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: payouts, error } = await client
            .from('payout_requests')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) throw error;

        if (payouts && payouts.length > 0) {
            tableBody.innerHTML = payouts.map(p => `
                <tr>
                    <td><small class="fw-bold text-dark">${p.user_id ? p.user_id.substring(0, 8) : 'عميل'}...</small></td>
                    <td class="fw-bold text-purple">${p.amount} ج.م</td>
                    <td><span class="badge bg-light text-dark border">${p.method === 'vodafone_cash' ? 'فودافون كاش' : p.method === 'instapay' ? 'إنستا باي' : 'أخرى'}</span></td>
                    <td class="fw-bold text-success">${p.account_details || '-'}</td>
                    <td>
                        <span class="badge ${p.status === 'approved' ? 'bg-success' : p.status === 'rejected' ? 'bg-danger' : 'bg-warning text-dark'} rounded-pill px-3 py-1">
                            ${p.status === 'approved' ? 'تم التحويل' : p.status === 'rejected' ? 'مرفوض' : 'معلق'}
                        </span>
                        ${p.hidden_for_user ? '<span class="badge bg-secondary ms-1 fs-9">مخفي عن المستخدم</span>' : ''}
                    </td>
                    <td>
                        ${p.status === 'pending' ? `
                            <button onclick="updatePayoutStatus('${p.id}')" class="btn btn-success btn-sm rounded-pill px-3 fs-8 me-1">موافقة وتحويل</button>
                            <button onclick="openRejectPayoutModal('${p.id}', '${p.user_id}', ${p.amount})" class="btn btn-outline-danger btn-sm rounded-pill px-2 fs-8 me-1">رفض</button>
                        ` : ''}
                        <div class="btn-group mt-1">
                            <button onclick="hidePayoutFromUser('${p.id}')" class="btn btn-outline-secondary btn-sm fs-9" title="إخفاء الرسالة من حساب العميل فقط">حذف لدى المستخدم <i class="bi bi-eye-slash"></i></button>
                            <button onclick="deletePayoutPermanently('${p.id}')" class="btn btn-danger btn-sm fs-9" title="حذف نهائي من قاعدة البيانات">حذف نهائي <i class="bi bi-trash"></i></button>
                        </div>
                    </td>
                </tr>
            `).join('');
        } else {
            tableBody.innerHTML = `<tr><td colspan="6" class="text-muted py-3">لا توجد طلبات سحب أو إثباتات تحويل حالياً</td></tr>`;
        }

    } catch (err) {
        console.warn('تنبيه طلبات السحب:', err.message);
        tableBody.innerHTML = `<tr><td colspan="6" class="text-muted py-3">لا توجد طلبات سحب معلقة حالياً</td></tr>`;
    }
}

window.hidePayoutFromUser = async function(payoutId) {
    const confirmed = await showAdminConfirm({
        title: 'إخفاء طلب السحب',
        message: 'هل تريد إخفاء هذا الطلب/الإثبات من واجهة العميل فقط مع الحفاظ عليه في الداتا بيز؟',
        confirmText: 'إخفاء الآن',
        type: 'warning'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { error } = await client
            .from('payout_requests')
            .update({ hidden_for_user: true })
            .eq('id', payoutId);

        if (error) throw error;

        showAdminToast('تم إخفاء الطلب من واجهة العميل بنجاح!', 'success');
        loadPayoutRequests();
    } catch (err) {
        showAdminToast('خطأ: ' + err.message, 'error');
    }
};

window.deletePayoutPermanently = async function(payoutId) {
    const confirmed = await showAdminConfirm({
        title: 'حذف طلب السحب نهائياً',
        message: '🚨 تحذير: هل أنت متأكد من حذف هذا الطلب والإثبات نهائياً من الداتا بيز؟',
        confirmText: 'حذف نهائي',
        type: 'danger'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { error } = await client
            .from('payout_requests')
            .delete()
            .eq('id', payoutId);

        if (error) throw error;

        showAdminToast('تم حذف إثبات التحويل/الطلب نهائياً من الداتا بيز!', 'success');
        loadPayoutRequests();
        loadAdminStats();
    } catch (err) {
        showAdminToast('خطأ أثناء الحذف النهائي: ' + err.message, 'error');
    }
};

function openRejectPayoutModal(requestId, userId, amount) {
    document.getElementById('rejectPayoutRequestId').value = requestId;
    document.getElementById('rejectPayoutUserId').value = userId;
    document.getElementById('rejectPayoutAmount').value = amount;
    document.getElementById('rejectAmountDisplay').innerText = amount;
    document.getElementById('rejectPayoutReason').value = '';

    const modal = new bootstrap.Modal(document.getElementById('rejectPayoutModal'));
    modal.show();
}

function initRejectPayoutFormListener() {
    const form = document.getElementById('rejectPayoutForm');
    if (!form) return;

    form.addEventListener('submit', async function (e) {
        e.preventDefault();
        e.stopImmediatePropagation();

        const requestId = document.getElementById('rejectPayoutRequestId').value;
        const reason = document.getElementById('rejectPayoutReason').value.trim();
        const submitBtn = form.querySelector('button[type="submit"]');

        if (!requestId) return;

        try {
            let client = window.supabaseClient;
            if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

            if (submitBtn) submitBtn.disabled = true;

            const { data: updatedReq, error: reqErr } = await client
                .from('payout_requests')
                .update({ status: 'rejected', rejection_reason: reason })
                .eq('id', requestId)
                .eq('status', 'pending')
                .select();

            if (reqErr) throw reqErr;

            if (!updatedReq || updatedReq.length === 0) {
                showAdminToast('⚠️ تمت معالجة هذا الطلب سابقاً في قاعدة البيانات.', 'warning');
                const modalEl = document.getElementById('rejectPayoutModal');
                const modal = bootstrap.Modal.getInstance(modalEl);
                if (modal) modal.hide();
                loadPayoutRequests();
                return;
            }

            showAdminToast('✅ تم رفض الطلب وتقوم قاعدة البيانات بإرجاع الرصيد تلقائياً!', 'success');

            const modalEl = document.getElementById('rejectPayoutModal');
            const modal = bootstrap.Modal.getInstance(modalEl);
            if (modal) modal.hide();

            loadPayoutRequests();
            loadUsersList();
            loadAdminStats();

        } catch (err) {
            console.error('Error rejecting payout:', err);
            showAdminToast('خطأ أثناء الرفض: ' + err.message, 'error');
        } finally {
            if (submitBtn) submitBtn.disabled = false;
        }
    });
}

async function updatePayoutStatus(requestId) {
    const confirmed = await showAdminConfirm({
        title: 'تأكيد السحب والتحويل',
        message: 'هل أنت متأكد من الموافقة على طلب السحب وتحويل المبلغ لحساب العميل؟',
        confirmText: 'موافقة وتحويل',
        type: 'purple'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: updatedReq, error: updateErr } = await client
            .from('payout_requests')
            .update({ status: 'approved' })
            .eq('id', requestId)
            .eq('status', 'pending')
            .select();

        if (updateErr) throw updateErr;

        if (!updatedReq || updatedReq.length === 0) {
            showAdminToast('⚠️ تمت معالجة هذا الطلب سابقاً.', 'warning');
            loadPayoutRequests();
            return;
        }

        showAdminToast('🎉 تم قبول طلب السحب وجاري تحديث الأرصدة تلقائياً في Supabase!', 'success');
        loadPayoutRequests();
        loadUsersList();
        loadAdminStats();

    } catch (err) {
        console.error('Error approving payout:', err);
        showAdminToast('حدث خطأ أثناء الموافقة: ' + err.message, 'error');
    }
}

async function loadUsersList() {
    const tableBody = document.getElementById('adminUsersTable');
    if (!tableBody) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: users, error } = await client
            .from('profiles')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) throw error;

        if (users && users.length > 0) {
            tableBody.innerHTML = users.map(u => `
                <tr>
                    <td class="fw-bold text-dark text-start">
                        <a href="javascript:void(0);" onclick="openDynamicUserProfile('${u.id}')" class="text-purple text-decoration-none fw-extrabold hover-underline d-block mb-1">
                            ${u.full_name || 'عميل أونلاين كشك'} <i class="bi bi-box-arrow-up-right ms-1 fs-9"></i>
                        </a>
                        <small class="text-muted fs-9 d-block">${u.phone || u.id.substring(0, 10)}</small>
                    </td>
                    <td>
                        <div class="fs-9 text-end d-inline-block">
                            <span class="d-block text-success">متاح: <strong>${u.available_balance || 0.00} ج.م</strong></span>
                            <span class="d-block text-purple">معلق: <strong>${u.total_earnings || 0.00} ج.م</strong></span>
                            <span class="d-block text-warning">بانتظار سحب: <strong>${u.pending_payout || 0.00} ج.م</strong></span>
                        </div>
                    </td>
                    <td>
                        <span class="badge ${u.status === 'frozen' ? 'bg-danger' : 'bg-success'} rounded-pill px-3 py-1">
                            ${u.status === 'frozen' ? 'مجمّد' : 'نشط'}
                        </span>
                    </td>
                    <td>
                        <button onclick="openManageUserBalanceModal('${u.id}')" class="btn btn-purple-pill btn-sm rounded-pill px-3 fs-9 fw-bold">
                            تعديل وإدارة الحساب <i class="bi bi-sliders ms-1"></i>
                        </button>
                    </td>
                </tr>
            `).join('');
        } else {
            tableBody.innerHTML = `<tr><td colspan="4" class="text-muted py-3">لا توجد عملاء مسجلين</td></tr>`;
        }
    } catch (err) {
        console.warn('تنبيه قائمة المستخدمين:', err.message);
        tableBody.innerHTML = `<tr><td colspan="4" class="text-muted py-3">جاري تحميل بيانات العملاء...</td></tr>`;
    }
}

window.openManageUserBalanceModal = async function(userId) {
    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: profile, error } = await client.from('profiles').select('*').eq('id', userId).single();
        if (error || !profile) throw new Error("تعذر جلب بيانات الحساب");

        document.getElementById('targetUserId').value = profile.id;
        document.getElementById('targetUserName').value = profile.full_name || 'عميل بدون اسم';
        document.getElementById('targetAvailableBalance').value = profile.available_balance || 0;
        document.getElementById('targetPendingBalance').value = profile.total_earnings || 0;
        document.getElementById('targetAwaitingBalance').value = profile.pending_payout || 0;
        document.getElementById('targetWithdrawnBalance').value = profile.total_withdrawn || 0;
        document.getElementById('targetUserStatus').value = profile.status || 'active';

        new bootstrap.Modal(document.getElementById('manageUserBalanceModal')).show();

    } catch (err) {
        showAdminToast('خطأ: ' + err.message, 'error');
    }
};

function initManageUserBalanceFormListener() {
    const form = document.getElementById('manageUserBalanceForm');
    if (!form) return;

    form.addEventListener('submit', async function (e) {
        e.preventDefault();
        e.stopImmediatePropagation();

        const userId = document.getElementById('targetUserId').value;
        const available = parseFloat(document.getElementById('targetAvailableBalance').value || '0');
        const pending = parseFloat(document.getElementById('targetPendingBalance').value || '0');
        const awaiting = parseFloat(document.getElementById('targetAwaitingBalance').value || '0');
        const withdrawn = parseFloat(document.getElementById('targetWithdrawnBalance').value || '0');
        const status = document.getElementById('targetUserStatus').value;

        try {
            let client = window.supabaseClient;
            if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

            const { error } = await client
                .from('profiles')
                .update({
                    available_balance: available,
                    total_earnings: pending,
                    pending_payout: awaiting,
                    total_withdrawn: withdrawn,
                    status: status
                })
                .eq('id', userId);

            if (error) throw error;

            showAdminToast('🎉 تم حفظ وتعديل الأرصدة يدوياً في الداتا بيز بنجاح تام!', 'success');

            const modalEl = document.getElementById('manageUserBalanceModal');
            const modal = bootstrap.Modal.getInstance(modalEl);
            if (modal) modal.hide();

            loadUsersList();

        } catch (err) {
            showAdminToast('خطأ في حفظ البيانات: ' + err.message, 'error');
        }
    });
}

window.openDynamicUserProfile = async function(userId) {
    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: profile, error } = await client.from('profiles').select('*').eq('id', userId).single();
        if (error || !profile) throw new Error("تعذر جلب بيانات العميل");

        document.getElementById('modalUserFullName').innerText = profile.full_name || 'غير محدد';
        document.getElementById('modalUserPhone').innerText = profile.phone || 'غير مضاف';
        document.getElementById('modalUserLocation').innerText = `${profile.state || 'المحافظة غير محددة'} / ${profile.city || 'المدينة غير محددة'}`;

        document.getElementById('modalUserEarnings').innerText = `${parseFloat(profile.total_earnings || 0).toFixed(2)} ج.م`;
        document.getElementById('modalUserAvailable').innerText = `${parseFloat(profile.available_balance || 0).toFixed(2)} ج.م`;
        document.getElementById('modalUserPending').innerText = `${parseFloat(profile.pending_payout || 0).toFixed(2)} ج.م`;
        document.getElementById('modalUserWithdrawn').innerText = `${parseFloat(profile.total_withdrawn || 0).toFixed(2)} ج.م`;

        const { data: payouts } = await client.from('payout_requests').select('*').eq('user_id', userId).order('created_at', { ascending: false });
        const historyTable = document.getElementById('modalUserHistoryTable');

        if (payouts && payouts.length > 0) {
            historyTable.innerHTML = payouts.map(p => `
                <tr>
                    <td>${new Date(p.created_at).toLocaleDateString('ar-EG')}</td>
                    <td class="fw-bold text-purple">${p.amount} ج.م</td>
                    <td>${p.method === 'vodafone_cash' ? 'فودافون كاش' : 'إنستا باي'}</td>
                    <td><span class="badge ${p.status === 'approved' ? 'bg-success' : p.status === 'rejected' ? 'bg-danger' : 'bg-warning text-dark'}">${p.status === 'approved' ? 'مكتمل' : p.status === 'rejected' ? 'مرفوض' : 'معلق'}</span></td>
                </tr>
            `).join('');
        } else {
            historyTable.innerHTML = `<tr><td colspan="4" class="text-muted py-2">لا توجد طلبات سحب مسجلة لهذا العميل.</td></tr>`;
        }

        new bootstrap.Modal(document.getElementById('adminUserProfileModal')).show();

    } catch (err) {
        showAdminToast('خطأ في جلب ملف العميل: ' + err.message, 'error');
    }
};

async function populateUsersDropdownForCommission() {
    const select = document.getElementById('commUserId');
    if (!select) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: users, error } = await client.from('profiles').select('id, full_name');
        if (error) throw error;

        if (users && users.length > 0) {
            select.innerHTML = users.map(u => `<option value="${u.id}">${u.full_name || 'عميل بدون اسم'} (${u.id.substring(0, 6)}...)</option>`).join('');
        } else {
            select.innerHTML = `<option value="">لا توجد عملاء مسجلين</option>`;
        }
    } catch (err) {
        select.innerHTML = `<option value="">خطأ في جلب العملاء</option>`;
    }
}

function initAddCommissionFormListener() {
    const form = document.getElementById('addCommissionForm');
    if (!form) return;

    form.addEventListener('submit', async function (e) {
        e.preventDefault();
        e.stopImmediatePropagation();

        const userId = document.getElementById('commUserId').value;
        const prodTitle = document.getElementById('commProductTitle').value.trim();
        const amount = parseFloat(document.getElementById('commAmount').value || '0');

        if (!userId || !prodTitle || amount <= 0) {
            showAdminToast('يرجى ملء جميع الحقول بقيم صحيحة', 'error');
            return;
        }

        try {
            let client = window.supabaseClient;
            if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

            const { error: commErr } = await client
                .from('commissions')
                .insert([{
                    affiliate_id: userId,
                    product_title: prodTitle,
                    amount: amount,
                    status: 'pending',
                    hidden_for_user: false
                }]);

            if (commErr) throw commErr;

            showAdminToast('🎉 تم تسجيل الكاش باك المعلق بنجاح للعميل وقاعدة البيانات تقوم بالتحديث!', 'success');
            
            const modalEl = document.getElementById('addCommissionModal');
            const modal = bootstrap.Modal.getInstance(modalEl);
            if (modal) modal.hide();
            form.reset();

            loadAdminCommissionsList();
            loadAdminStats();

        } catch (err) {
            showAdminToast('خطأ أثناء تسجيل العمولة: ' + err.message, 'error');
        }
    });
}

async function loadAdminCommissionsList() {
    const tableBody = document.getElementById('adminCommissionsTable');
    if (!tableBody) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: comms, error } = await client
            .from('commissions')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) throw error;

        if (comms && comms.length > 0) {
            tableBody.innerHTML = comms.map(c => `
                <tr>
                    <td>${new Date(c.created_at).toLocaleDateString('ar-EG')}</td>
                    <td><small class="fw-bold text-dark">عميل (${c.affiliate_id ? c.affiliate_id.substring(0, 8) : 'عام'})...</small></td>
                    <td class="fw-bold">${c.product_title || 'شراء منتج أفيليت'}</td>
                    <td class="fw-bold text-purple">${c.amount} ج.م</td>
                    <td>
                        <span class="badge ${c.status === 'approved' ? 'bg-success' : c.status === 'rejected' ? 'bg-danger' : 'bg-warning text-dark'} rounded-pill px-3 py-1">
                            ${c.status === 'approved' ? 'مقبول (أُضيف للرصيد)' : c.status === 'rejected' ? 'مرفوض' : 'معلق (بانتظار الموافقة)'}
                        </span>
                        ${c.hidden_for_user ? '<span class="badge bg-secondary ms-1 fs-9">مخفي عن العميل</span>' : ''}
                    </td>
                    <td>
                        ${c.status === 'pending' ? `
                            <button onclick="approveAdminCommission('${c.id}')" class="btn btn-success btn-sm rounded-pill px-3 fs-8 me-1">موافقة وإضافة للرصيد <i class="bi bi-check-lg"></i></button>
                            <button onclick="rejectAdminCommission('${c.id}')" class="btn btn-outline-danger btn-sm rounded-pill px-2 fs-8 me-1">رفض</button>
                        ` : ''}
                        <div class="btn-group mt-1">
                            <button onclick="hideCommissionFromUser('${c.id}')" class="btn btn-outline-secondary btn-sm fs-9" title="إخفاء الرسالة من حساب العميل فقط">حذف لدى المستخدم <i class="bi bi-eye-slash"></i></button>
                            <button onclick="deleteCommissionPermanently('${c.id}')" class="btn btn-danger btn-sm fs-9" title="حذف نهائي من قاعدة البيانات">حذف نهائي <i class="bi bi-trash"></i></button>
                        </div>
                    </td>
                </tr>
            `).join('');
        } else {
            tableBody.innerHTML = `<tr><td colspan="6" class="text-muted py-3">لا توجد عمليات شراء أو كاش باك مسجلة حالياً</td></tr>`;
        }

    } catch (err) {
        tableBody.innerHTML = `<tr><td colspan="6" class="text-muted py-3">لا توجد عمولات معلقة حالياً</td></tr>`;
    }
}

window.hideCommissionFromUser = async function(commId) {
    const confirmed = await showAdminConfirm({
        title: 'إخفاء العمولة',
        message: 'هل تريد إخفاء رسالة الكاش باك/العمولة هذه من واجهة المستخدم؟',
        confirmText: 'إخفاء الرسالة',
        type: 'warning'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { error } = await client
            .from('commissions')
            .update({ hidden_for_user: true })
            .eq('id', commId);

        if (error) throw error;

        showAdminToast('تم إخفاء الرسالة من واجهة العميل بنجاح!', 'success');
        loadAdminCommissionsList();
    } catch (err) {
        showAdminToast('خطأ في الإخفاء: ' + err.message, 'error');
    }
};

window.deleteCommissionPermanently = async function(commId) {
    const confirmed = await showAdminConfirm({
        title: 'حذف العمولة نهائياً',
        message: '🚨 تحذير: هل أنت متأكد من حذف هذه العمولة/الرسالة نهائياً من قاعدة البيانات؟',
        confirmText: 'حذف نهائي',
        type: 'danger'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { error } = await client
            .from('commissions')
            .delete()
            .eq('id', commId);

        if (error) throw error;

        showAdminToast('تم حذف العمولة نهائياً من قاعدة البيانات!', 'success');
        loadAdminCommissionsList();
        loadAdminStats();
    } catch (err) {
        showAdminToast('خطأ في الحذف النهائي: ' + err.message, 'error');
    }
};

window.approveAdminCommission = async function(commId) {
    const confirmed = await showAdminConfirm({
        title: 'الموافقة على الكاش باك',
        message: 'هل أنت متأكد من الموافقة على عمولة الكاش باك ونقلها لرصيد العميل المتاح للسحب؟',
        confirmText: 'موافقة وإضافة',
        type: 'purple'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: updatedComm, error: commErr } = await client
            .from('commissions')
            .update({ status: 'approved' })
            .eq('id', commId)
            .eq('status', 'pending')
            .select();

        if (commErr) throw commErr;

        if (!updatedComm || updatedComm.length === 0) {
            showAdminToast('⚠️ تمت معالجة هذه العمولة سابقاً.', 'warning');
            loadAdminCommissionsList();
            return;
        }

        showAdminToast('🎉 تمت الموافقة على العمولة وتقوم قاعدة البيانات بنقل الأرصدة تلقائياً!', 'success');
        loadAdminCommissionsList();
        loadUsersList();
        loadAdminStats();

    } catch (err) {
        showAdminToast('خطأ أثناء الموافقة: ' + err.message, 'error');
    }
};

window.rejectAdminCommission = async function(commId) {
    const confirmed = await showAdminConfirm({
        title: 'رفض العمولة',
        message: 'هل أنت متأكد من رفض هذه العمولة؟',
        confirmText: 'رفض العمولة',
        type: 'danger'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: updatedComm, error: commErr } = await client
            .from('commissions')
            .update({ status: 'rejected' })
            .eq('id', commId)
            .eq('status', 'pending')
            .select();

        if (commErr) throw commErr;

        if (!updatedComm || updatedComm.length === 0) {
            showAdminToast('⚠️ تمت معالجة هذه العمولة سابقاً.', 'warning');
            loadAdminCommissionsList();
            return;
        }

        showAdminToast('✅ تم رفض العمولة وتحديث الرصيد المعلق تلقائياً بواسطة قاعدة البيانات!', 'success');
        loadAdminCommissionsList();
        loadUsersList();
        loadAdminStats();

    } catch (err) {
        showAdminToast('خطأ أثناء الرفض: ' + err.message, 'error');
    }
};

async function loadCategoriesList() {
    const container = document.getElementById('adminCategoriesList');
    if (!container) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: categories, error } = await client.from('categories').select('*').order('name');
        if (error) throw error;

        if (categories && categories.length > 0) {
            container.innerHTML = categories.map(c => `
                <span class="badge bg-purple-soft text-purple fs-8 p-2 rounded-pill d-inline-flex align-items-center gap-2 border border-purple-subtle shadow-sm">
                    ${c.name} ${c.show_in_home !== false ? '<small class="text-success fw-normal" title="يظهر بالرئيسية">(بالرئيسية)</small>' : '<small class="text-muted fw-normal">(مخفي)</small>'}
                    <i onclick="deleteCategory('${c.id}')" class="bi bi-x-circle-fill text-danger cursor-pointer" title="حذف القسم"></i>
                </span>
            `).join('');
        } else {
            container.innerHTML = `<span class="text-muted fs-8">لا توجد أقسام مضافة بعد...</span>`;
        }
    } catch (err) {
        console.warn('تنبيه الأقسام:', err.message);
        container.innerHTML = `<span class="text-muted fs-8">لا توجد أقسام مضافة بعد...</span>`;
    }
}

async function loadStoresList() {
    const container = document.getElementById('adminStoresList');
    if (!container) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: stores, error } = await client.from('stores').select('*').order('name');
        if (error) throw error;

        if (stores && stores.length > 0) {
            container.innerHTML = stores.map(s => `
                <div class="badge bg-light text-dark fs-8 p-2 rounded-3 border d-inline-flex align-items-center gap-2 shadow-sm">
                    <span class="fw-bold text-purple">${s.name}</span>
                    <span class="badge ${s.show_in_stores_page !== false ? 'bg-success-subtle text-success' : 'bg-secondary-subtle text-secondary'} fs-9">
                        ${s.show_in_stores_page !== false ? 'صفحة المتاجر ✓' : 'مخفي'}
                    </span>
                    <span class="badge ${s.show_in_navbar !== false ? 'bg-primary-subtle text-primary' : 'bg-secondary-subtle text-secondary'} fs-9">
                        ${s.show_in_navbar !== false ? 'الناف بار ✓' : 'مخفي'}
                    </span>
                    <i onclick="deleteStore('${s.id}')" class="bi bi-trash-fill text-danger cursor-pointer ms-1" title="حذف المتجر"></i>
                </div>
            `).join('');
        } else {
            container.innerHTML = `<span class="text-muted fs-8">لا توجد متاجر مضافة حالياً...</span>`;
        }
    } catch (err) {
        console.warn('تنبيه المتاجر:', err.message);
        container.innerHTML = `<span class="text-muted fs-8">لا توجد متاجر مضافة حالياً...</span>`;
    }
}

async function deleteCategory(catId) {
    const confirmed = await showAdminConfirm({
        title: 'حذف القسم',
        message: 'هل أنت متأكد من حذف هذا القسم؟',
        confirmText: 'حذف',
        type: 'danger'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { error } = await client.from('categories').delete().eq('id', catId);
        if (error) throw error;

        showAdminToast('تم حذف القسم بنجاح!', 'success');
        loadCategoriesList();
        loadCategoriesAndStoresDropdowns();
    } catch (err) {
        showAdminToast('خطأ في حذف القسم: ' + err.message, 'error');
    }
}

async function deleteStore(storeId) {
    const confirmed = await showAdminConfirm({
        title: 'حذف المتجر',
        message: 'هل أنت متأكد من حذف هذا المتجر؟',
        confirmText: 'حذف المتجر',
        type: 'danger'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { error } = await client.from('stores').delete().eq('id', storeId);
        if (error) throw error;

        showAdminToast('تم حذف المتجر بنجاح!', 'success');
        loadStoresList();
        loadCategoriesAndStoresDropdowns();
    } catch (err) {
        showAdminToast('خطأ في حذف المتجر: ' + err.message, 'error');
    }
}

async function loadBannersList() {
    const tableBody = document.getElementById('adminBannersTable');
    if (!tableBody) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: banners, error } = await client.from('banners').select('*').order('created_at', { ascending: false });
        if (error) throw error;

        if (banners && banners.length > 0) {
            tableBody.innerHTML = banners.map(b => `
                <tr>
                    <td><img src="${b.image_url}" height="40" class="rounded-3 shadow-sm object-fit-cover" onerror="this.src='https://via.placeholder.com/100x40?text=Banner'"></td>
                    <td><small class="text-truncate d-inline-block max-w-200 text-muted">${b.target_link || '#'}</small></td>
                    <td><button onclick="deleteBanner('${b.id}')" class="btn btn-outline-danger btn-sm rounded-pill px-2 fs-9">حذف <i class="bi bi-trash"></i></button></td>
                </tr>
            `).join('');
        } else {
            tableBody.innerHTML = `<tr><td colspan="3" class="text-muted py-3">لا توجد بنرات بالسلايدر</td></tr>`;
        }
    } catch (err) {
        tableBody.innerHTML = `<tr><td colspan="3" class="text-muted py-3">لا توجد بنرات بالسلايدر</td></tr>`;
    }
}

async function deleteBanner(id) {
    const confirmed = await showAdminConfirm({
        title: 'حذف البانر',
        message: 'هل أنت متأكد من حذف هذا البانر من السلايدر؟',
        confirmText: 'حذف البانر',
        type: 'danger'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { error } = await client.from('banners').delete().eq('id', id);
        if (error) throw error;

        showAdminToast('تم حذف البانر بنجاح!', 'success');
        loadBannersList();
    } catch (err) {
        showAdminToast('خطأ في الحذف: ' + err.message, 'error');
    }
}

async function loadNewsletterSubscribers() {
    const tableBody = document.getElementById('adminNewsletterTable');
    if (!tableBody) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: subs, error } = await client.from('newsletter_subscribers').select('*').order('created_at', { ascending: false });
        if (error) throw error;

        if (subs && subs.length > 0) {
            tableBody.innerHTML = subs.map(s => `
                <tr>
                    <td class="fw-bold text-dark">${s.email}</td>
                    <td class="text-muted fs-9">${s.created_at ? new Date(s.created_at).toLocaleDateString('ar-EG') : 'الآن'}</td>
                </tr>
            `).join('');
        } else {
            tableBody.innerHTML = `<tr><td colspan="2" class="text-muted py-3">لا يوجد مشتركين بالنشرة حتى الآن</td></tr>`;
        }
    } catch (err) {
        tableBody.innerHTML = `<tr><td colspan="2" class="text-muted py-3">لا يوجد مشتركين بالنشرة حتى الآن</td></tr>`;
    }
}

// 🌟 عرض رسائل التواصل وتفاصيلها الكاملة بداخل المودال التفصيلي
async function loadContactMessages() {
    const tableBody = document.getElementById('adminContactMessagesTable');
    if (!tableBody) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: msgs, error } = await client.from('contact_messages').select('*').order('created_at', { ascending: false });
        if (error) throw error;

        if (msgs && msgs.length > 0) {
            tableBody.innerHTML = msgs.map(m => {
                const shortMsg = m.message && m.message.length > 25 ? m.message.substring(0, 25) + '...' : (m.message || '-');
                return `
                <tr>
                    <td class="text-start">
                        <strong class="d-block text-dark fs-8">${m.name || 'زائر'}</strong>
                        <small class="text-muted fs-9">${m.email || '-'}</small>
                    </td>
                    <td class="text-start fs-8 text-secondary">
                        <strong class="d-block text-purple fs-9">${m.subject || 'استفسار عام'}</strong>
                        ${shortMsg}
                    </td>
                    <td><span class="badge bg-light text-dark border fs-9">${m.created_at ? new Date(m.created_at).toLocaleDateString('ar-EG') : 'الآن'}</span></td>
                    <td>
                        <button onclick="viewContactMessageDetails('${m.id}')" class="btn btn-purple-soft btn-sm rounded-pill px-3 fs-9 fw-bold">
                            التفاصيل <i class="bi bi-eye ms-1"></i>
                        </button>
                    </td>
                </tr>
            `;
            }).join('');
        } else {
            tableBody.innerHTML = `<tr><td colspan="4" class="text-muted py-3">لا توجد رسائل جديدة</td></tr>`;
        }
    } catch (err) {
        tableBody.innerHTML = `<tr><td colspan="4" class="text-muted py-3">لا توجد رسائل جديدة</td></tr>`;
    }
}

window.viewContactMessageDetails = async function(messageId) {
    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { data: msg, error } = await client.from('contact_messages').select('*').eq('id', messageId).single();
        if (error || !msg) throw new Error("تعذر جلب تفاصيل الرسالة");

        document.getElementById('msgModalName').innerText = msg.name || 'زائر';
        if (document.getElementById('msgModalPhone')) document.getElementById('msgModalPhone').innerText = msg.phone || 'غير مضاف';
        document.getElementById('msgModalEmail').value = msg.email || '-';
        if (document.getElementById('msgModalSubject')) document.getElementById('msgModalSubject').value = msg.subject || 'استفسار عام';
        document.getElementById('msgModalDate').innerText = msg.created_at ? new Date(msg.created_at).toLocaleString('ar-EG') : 'الآن';
        document.getElementById('msgModalContent').innerText = msg.message || 'لا يوجد نص.';

        const replyBtn = document.getElementById('msgModalReplyBtn');
        if (replyBtn) {
            replyBtn.href = `mailto:${msg.email}?subject=${encodeURIComponent('رد على: ' + (msg.subject || 'استفسارك في أونلاين كشك'))}`;
        }

        const deleteBtn = document.getElementById('msgModalDeleteBtn');
        if (deleteBtn) {
            deleteBtn.onclick = function() { deleteContactMessage(msg.id); };
        }

        const modalEl = document.getElementById('contactMessageDetailsModal');
        if (modalEl && typeof bootstrap !== 'undefined') {
            const modal = new bootstrap.Modal(modalEl);
            modal.show();
        }

    } catch (err) {
        showAdminToast('خطأ: ' + err.message, 'error');
    }
};

async function deleteContactMessage(messageId) {
    const confirmed = await showAdminConfirm({
        title: 'حذف الرسالة',
        message: 'هل أنت متأكد من حذف هذه الرسالة؟',
        confirmText: 'حذف',
        type: 'danger'
    });
    if (!confirmed) return;

    try {
        let client = window.supabaseClient;
        if (!client && window.supabase && typeof SUPABASE_URL !== 'undefined') client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

        const { error } = await client.from('contact_messages').delete().eq('id', messageId);
        if (error) throw error;

        showAdminToast('تم حذف الرسالة بنجاح!', 'success');

        const modalEl = document.getElementById('contactMessageDetailsModal');
        if (modalEl && typeof bootstrap !== 'undefined') {
            const modal = bootstrap.Modal.getInstance(modalEl);
            if (modal) modal.hide();
        }

        loadContactMessages();

    } catch (err) {
        showAdminToast('خطأ أثناء الحذف: ' + err.message, 'error');
    }
}

function showAdminToast(message, type = 'success') {
    const existing = document.querySelector('.admin-toast-custom');
    if (existing) existing.remove();

    const toast = document.createElement('div');
    toast.className = `admin-toast-custom admin-toast-${type} animate-slide-in`;
    toast.innerHTML = `
        <div class="d-flex align-items-center gap-2">
            <i class="bi ${type === 'success' ? 'bi-check-circle-fill' : 'bi-exclamation-triangle-fill'} fs-5"></i>
            <span class="fw-medium fs-8">${message}</span>
        </div>
        <button type="button" class="btn-close btn-close-white ms-auto fs-9" onclick="this.parentElement.remove()"></button>
    `;
    document.body.appendChild(toast);

    setTimeout(() => { toast.remove(); }, 4000);
}

function showAdminConfirm({ title = 'تأكيد الإجراء', message = 'هل أنت تأكد من الاستمرار؟', confirmText = 'نعم، تأكيد', cancelText = 'إلغاء', type = 'danger' }) {
    return new Promise((resolve) => {
        const oldModal = document.getElementById('adminCustomConfirmModal');
        if (oldModal) oldModal.remove();

        const btnClass = type === 'danger' ? 'btn-danger' : 'btn-purple';

        const modalHtml = `
            <div class="modal fade show d-block" id="adminCustomConfirmModal" tabindex="-1" style="background: rgba(15, 23, 42, 0.6); backdrop-filter: blur(4px); z-index: 1090;">
                <div class="modal-dialog modal-dialog-centered modal-sm">
                    <div class="modal-content border-0 shadow-lg rounded-4 overflow-hidden">
                        <div class="modal-body p-4 text-center">
                            <h6 class="fw-bold text-dark mb-2">${title}</h6>
                            <p class="text-muted fs-8 mb-4">${message}</p>
                            <div class="d-flex gap-2 justify-content-center">
                                <button type="button" class="btn btn-light rounded-pill px-3 fs-8 fw-semibold flex-fill" id="btnConfirmCancel">${cancelText}</button>
                                <button type="button" class="btn ${btnClass} rounded-pill px-3 fs-8 fw-semibold flex-fill" id="btnConfirmOk">${confirmText}</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        `;

        document.body.insertAdjacentHTML('beforeend', modalHtml);

        const modalEl = document.getElementById('adminCustomConfirmModal');
        const btnOk = document.getElementById('btnConfirmOk');
        const btnCancel = document.getElementById('btnConfirmCancel');

        const closeConfirm = (result) => {
            modalEl.classList.remove('show');
            setTimeout(() => {
                modalEl.remove();
                resolve(result);
            }, 200);
        };

        btnOk.addEventListener('click', () => closeConfirm(true));
        btnCancel.addEventListener('click', () => closeConfirm(false));
    });
}